# Generated by Django 5.1.1 on 2024-10-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Publicaciones'},
        ),
    ]
